_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  system__admin:
    menu_name: admin
    parent: ''
    weight: 1
    expanded: false
    enabled: true
  system__admin_content:
    menu_name: admin
    parent: system.admin
    weight: -97
    expanded: false
    enabled: true
  system__admin_structure:
    menu_name: admin
    parent: system.admin
    weight: -96
    expanded: false
    enabled: true
  system__themes_page:
    menu_name: admin
    parent: system.admin
    weight: -95
    expanded: false
    enabled: true
  system__modules_list:
    menu_name: admin
    parent: system.admin
    weight: -94
    expanded: false
    enabled: true
  system__admin_config:
    menu_name: admin
    parent: system.admin
    weight: -93
    expanded: false
    enabled: true
  entity__user__collection:
    menu_name: admin
    parent: system.admin
    weight: -92
    expanded: false
    enabled: true
  system__admin_reports:
    menu_name: admin
    parent: system.admin
    weight: -91
    expanded: false
    enabled: true
  help__main:
    menu_name: admin
    parent: system.admin
    weight: -90
    expanded: false
    enabled: true
  announcements_feed__announcement:
    menu_name: admin
    parent: system.admin
    weight: -89
    expanded: false
    enabled: true
  jwt_auto_login__markets_menu:
    menu_name: admin
    parent: system.admin
    weight: -99
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__taxonomy_vocabulary__add_form':
    menu_name: admin
    parent: entity.taxonomy_vocabulary.collection
    weight: 11
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__taxonomy_vocabulary__overview_form__content_hierarchy':
    menu_name: admin
    parent: entity.taxonomy_vocabulary.collection
    weight: 12
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__taxonomy_vocabulary__overview_form__tags':
    menu_name: admin
    parent: entity.taxonomy_vocabulary.collection
    weight: 13
    expanded: false
    enabled: true
