_core:
  default_config_hash: FLJZME3II5fjmMSrdEvJHp95ZJf8V_X0jbX0VdVU1BU
shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: ewmrweb
    pass: CYyoVOnJFlIl
allow_cli: true
debug_header: false
unset_basic_auth_headers: true
print: Hello!
method: 0
paths: ''
allowlist: ''
http_method_allowlist: {  }
domains: "wmr-hq-main.ddev.site\r\nwmr-hq-main.ddev.site/wmr-usavan"
